name = "warp"
main = "src/index.ts"
compatibility_date = "2023-08-23"

[[d1_databases]]
binding = "DATABASE"
database_name = "warp-db"
database_id = "4ca7dbc7-74ff-42be-9f86-965dfed62ad7"

[triggers]
crons = [
    '*/5 * * * *', # every five minute
    '*/10 * * * *' # every ten minute
]

