name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
          version: latest
          run_install: false
    - uses: cloudflare/wrangler-action@v3
      with:
        packageManager: pnpm
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        postCommands: |
          # Create sqlite tables if not exists
          wrangler d1 execute warp-db --file=./schema.sql
        secrets: |
          SECRET_KEY
          LOSS_THRESHOLD
          DELAY_THRESHOLD
          RANDOM_COUNT
          GET_DATA_INTERVAL
          SAVE_ACCOUNT_INTERVAL
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        LOSS_THRESHOLD: ${{ secrets.LOSS_THRESHOLD || 10 }}
        DELAY_THRESHOLD: ${{ secrets.DELAY_THRESHOLD || 500 }}
        RANDOM_COUNT: ${{ secrets.RANDOM_COUNT || 10 }}
        GET_DATA_INTERVAL: ${{ secrets.GET_DATA_INTERVAL || 2 }}
        SAVE_ACCOUNT_INTERVAL: ${{ secrets.SAVE_ACCOUNT_INTERVAL || 10 }}

